sudo: required
services:
  - docker

before_install:
  - docker build -t testadmin/dockerwithci -f Dockerfile.dev .

script:
  - docker run -e CI=true testadmin/dockerwithci npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-admin"
  env: "DockerReactAdmin-env"
  bucket_name: "elasticbeanstalk-us-east-2-383263263565"
  bucket_path: "docker-react-admin"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY